workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_pro
    cache:
      cache_paths:
        - $HOME/.gradle/caches
    environment:
      groups:
        - keystore_credentials # <-- Includes - CM_KEYSTORE, CM_KEYSTORE_PASSWORD, CM_KEY_PASSWORD, CM_KEY_ALIAS
      # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
      vars:
        CM_KEYSTORE_PATH: /tmp/keystore.keystore
      node: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
        - pattern: develop
          include: false
      cancel_previous_builds: false
    scripts:
      - name: Set up key.properties file for code signing
        script: |
          # !/usr/bin/env zsh 
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
          cat >> "$CM_BUILD_DIR/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF
      - name: Set up local properties
        script: |
          #!/usr/bin/env zsh 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build aab Android app
        script: |
          #!/usr/bin/env zsh 
          chmod +x gradlew
          ./gradlew bundleRelease # To generate an .apk use--> ./gradlew assembleRelease
      - name: Build apk Android app
        script: |
          #!/usr/bin/env zsh 
          ./gradlew assembleRelease # To generate an .apk use--> ./gradlew assembleRelease
      - name: Check app cert
        script: |
          #!/usr/bin/env zsh 
          jarsigner -verify -verbose -certs $FCI_BUILD_OUTPUT_DIR/*.apk
    artifacts:
      - app/build/outputs/**/**/*.aab
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - mohammed@nevercode.io
        notify:
          success: false
          failure: false
      slack:
        channel: "#test-codemagic1"
        notify_on_build_start: true
    #   google_play:
    #     credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    #     track: internal
